security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        api:
            pattern: ^/v1/api
            stateless: true
            custom_authenticators:
                - App\Security\BearerTokenAuthenticator

    access_control:
        - { path: ^/v1/api, roles: [ROLE_USER, ROLE_ROOT] }
